language: android
dist: trusty

android:
  components:
    # The BuildTools version used by the project
    - build-tools-29.0.3

    # The SDK version used to compile the project
    - android-30

before_install:
  - yes | sdkmanager "platforms;android-30"

script:
 - ./gradlew build
 - ./gradlew assembleDebug
 
notifications:
  email: false
