language: android
dist: trusty

android:
  components:
    # The BuildTools version used by the project
    - build-tools-29.0.3

    # The SDK version used to compile the project
    - android-29

    # Additional components
    - extra-google-google_play_services

    # Specify at least one system image,
    # if you need to run emulator(s) during tests
    #- sys-img-x86-android-29
script:
 - ./gradlew build
 - ./gradlew assembleDebug
 - ls -lah